apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: eks-122
  region: ap-northeast-2
  version: "1.22"

nodeGroups:
  - name: ng-1
    instanceType: m5.large
    desiredCapacity: 3
    volumeSize: 100
    volumeType: gp3
  - name: ng-2
    instanceType: m5.xlarge
    desiredCapacity: 3
    volumeSize: 100
    volumeType: gp3